### ISSUE TITLE
Jekyll not updating site automatically

### ISSUE THREAD

**Issue by patient112** [patient112/Patient112.github.io#1]
Try the following:
Create .yml file within  folder called github_workflows.
```
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Set to your Jekyll site's Ruby version
    - name: Build and deploy
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```
